
server:
  type: simple
  applicationContextPath: /zmittag
  connector:
    type: http
    port: 8080


logging:
  level: DEBUG
  appenders:
    - type: console
      threshold: ALL
      target: stderr
