
server:
  type: simple
  applicationContextPath: /zmittag
  connector:
    type: http
    port: 80


logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: /home/joerg/log/zmittag.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /home/joerg/log/zmittag-%d.log
      archivedFileCount: 5
      timeZone: UTC
